- name: Terminal Environment
  hosts: localhost
  vars:
    me: "mthorning"
    email: "matthewthorning@gmail.com"
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  - name: Install dependencies
    become: true
    package:
      state: present
      name: 
        - curl
        - stow
        - git
        - build-essential
  tasks: 
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/packages.yml
    - include: tasks/neovim.yml

