- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:{{ me }}/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
- name: Stow dotfiles
  shell: cd /home/{{ me }}/dotfiles && ./stow-ubuntu
- name: Stow dotfiles for root
  become: true
  shell: cd /home/{{ me }}/dotfiles && ./stow-ubuntu-root


